# Generated by Django 5.0.1 on 2024-01-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firs_name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "lasts_name",
                    models.CharField(max_length=30, verbose_name="Apellido"),
                ),
            ],
        ),
    ]
