# Generated by Django 5.0.1 on 2024-01-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0002_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "Reviewd"),
                    ("N", "Not Reviewd"),
                    ("E", "Error"),
                    ("A", "Accepted"),
                ],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
