# Generated by Django 5.0.1 on 2024-01-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0003_website_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "name",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
