# Generated by Django 5.0.1 on 2024-01-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0004_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
