# Generated by Django 5.0.1 on 2024-01-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0005_alter_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cars",
            field=models.ManyToManyField(
                to="userApp.car", verbose_name="Carros del usuario"
            ),
        ),
    ]
